# Generated by Django 4.2.7 on 2023-11-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_info_delete_post"),
    ]

    operations = [
        migrations.RemoveField(model_name="info", name="author",),
        migrations.RemoveField(model_name="info", name="birth_date",),
        migrations.RemoveField(model_name="info", name="phone_num",),
        migrations.RemoveField(model_name="info", name="text",),
        migrations.AlterField(
            model_name="info", name="name", field=models.CharField(max_length=200),
        ),
    ]
