# Generated by Django 4.2.7 on 2023-11-23 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_remove_info_author_remove_info_birth_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="info",
            name="birth_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="info",
            name="phone_num",
            field=models.CharField(default=89000000000, max_length=12),
        ),
        migrations.AddField(
            model_name="info",
            name="photo",
            field=models.ImageField(default="null", upload_to="static/img/pics"),
        ),
        migrations.AddField(
            model_name="info", name="sex1", field=models.BooleanField(default="True"),
        ),
        migrations.AddField(
            model_name="info", name="sex2", field=models.BooleanField(default="False"),
        ),
        migrations.AddField(
            model_name="info", name="text", field=models.TextField(default=""),
        ),
    ]
