# Generated by Django 4.2.7 on 2023-11-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_info_birth_date_info_phone_num_info_photo_info_sex1_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="info", name="sex1",),
        migrations.RemoveField(model_name="info", name="sex2",),
        migrations.AddField(
            model_name="info",
            name="sex",
            field=models.CharField(
                choices=[("M", "Парень"), ("F", "Девушка")],
                default="",
                max_length=1,
                verbose_name="Пол",
            ),
        ),
        migrations.AlterField(
            model_name="info", name="birth_date", field=models.DateField(default=""),
        ),
        migrations.AlterField(
            model_name="info",
            name="phone_num",
            field=models.CharField(default="", max_length=12),
        ),
    ]
